# Generated by Django 3.2.7 on 2021-10-05 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0002_auto_20210929_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.TextField(default='No text', verbose_name='Ответ на вопрос'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='general',
            field=models.BooleanField(default=False, verbose_name='Отображать на стартовой странице'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=30, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='relation_question',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Основной_вопрос', to='FAQ.questions', verbose_name='Основной вопрос'),
        ),
        migrations.AlterField(
            model_name='relation_question',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Дополнительный_вопрос', to='FAQ.questions', verbose_name='Дополнительный вопрос'),
        ),
    ]
