# Generated by Django 3.2.7 on 2021-12-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0006_auto_20211119_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='settings_bot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title_question', models.TextField(default='Добрый день!\nКакой у вас воопрос?', verbose_name='Титульное сообщение')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
            ],
        ),
    ]
