# Generated by Django 3.2.7 on 2021-12-19 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FAQ', '0011_auto_20211219_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings_bot',
            name='token',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='settings_bot',
            name='user',
            field=models.ForeignKey(default='auth.User', on_delete=django.db.models.deletion.CASCADE, related_name='settings_bots', to=settings.AUTH_USER_MODEL),
        ),
    ]
