# Generated by Django 3.2.7 on 2021-12-20 10:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0014_settings_bot_bot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='bot',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='Бот', to='FAQ.settings_bot', verbose_name='Бот'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings_bot',
            name='status',
            field=models.CharField(choices=[('включен', 'Включен'), ('выключен', 'Выключен')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='settings_bot',
            name='other_button_row',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)], verbose_name='Количество столбцов кнопок дополнительных вопросов'),
        ),
        migrations.AlterField(
            model_name='settings_bot',
            name='title_button_row',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)], verbose_name='Количество столбцов кнопок титульного вопроса'),
        ),
    ]
