# Generated by Django 3.2.7 on 2022-01-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0015_auto_20211220_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings_bot',
            name='status',
            field=models.CharField(choices=[('включен', 'Включен'), ('выключен', 'Выключен'), ('неверный токен', 'Неверный токен')], default='выключен', max_length=20),
        ),
    ]
