# Generated by Django 3.2.7 on 2022-01-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0017_auto_20220119_1438'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relationquestion',
            unique_together={('base', 'sub')},
        ),
    ]
