# Generated by Django 3.2.7 on 2022-02-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0018_alter_relationquestion_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsbot',
            name='bot_name',
            field=models.CharField(max_length=50, verbose_name='Название бота'),
        ),
    ]
