# Generated by Django 3.2.7 on 2021-12-19 12:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FAQ', '0010_auto_20211218_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings_bot',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='settings_bots', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings_bot',
            name='interval_refresh_base',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Интервал синхронизации вопросов в сек'),
        ),
    ]
