# Generated by Django 3.2.7 on 2021-10-05 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0004_auto_20211005_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ('-id',), 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='relation_question',
            options={'verbose_name': 'Таблица связей вопросов', 'verbose_name_plural': 'Таблица связей вопросов'},
        ),
    ]
