# Generated by Django 3.2.7 on 2021-12-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0008_alter_settings_bot_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings_bot',
            name='token',
            field=models.CharField(default='', max_length=50),
        ),
    ]
