# Generated by Django 3.2.7 on 2021-12-18 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0009_settings_bot_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings_bot',
            name='interval_refresh_base',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Интервал обновления вопросов из базы данных'),
        ),
        migrations.AddField(
            model_name='settings_bot',
            name='other_button_row',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)], verbose_name='Количество кнопок дополнительных вопросов'),
        ),
        migrations.AddField(
            model_name='settings_bot',
            name='title_button_row',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)], verbose_name='Количество кнопок титульного вопроса'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Изменен'),
        ),
        migrations.AlterField(
            model_name='relation_question',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Изменен'),
        ),
        migrations.AlterField(
            model_name='settings_bot',
            name='token',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='settings_bot',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Изменен'),
        ),
    ]
