# Generated by Django 3.2.7 on 2021-12-19 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FAQ', '0012_auto_20211219_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings_bot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_bots', to=settings.AUTH_USER_MODEL),
        ),
    ]
