# Generated by Django 4.0.6 on 2022-07-04 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0019_alter_settingsbot_bot_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingsbot',
            options={'ordering': ('status', '-id'), 'verbose_name': 'Настройки бота', 'verbose_name_plural': 'Настройки бота'},
        ),
        migrations.AlterField(
            model_name='settingsbot',
            name='bot_name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='settingsbot',
            name='interval_refresh_base',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(20)], verbose_name='Интервал синхронизации вопросов в сек'),
        ),
        migrations.AlterField(
            model_name='settingsbot',
            name='status',
            field=models.CharField(choices=[('включен', 'Включен'), ('выключен', 'Выключен'), ('неверный токен', 'Неверный токен')], default='выключен', max_length=20, verbose_name='Статус'),
        ),
    ]
